import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/Shared/Navbar";
import Sidebar from "@/components/Sidebar/Sidebar";
import Footer from "@/components/Shared/Footer";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Fit Pulse",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased `}
      >
        <div className="flex h-screen bg-gradient-to-r from-gray-200 via-gray-100 to-gray-200">
          {/* Sidebar */}
          <div className="">
            <Sidebar />
          </div>

          {/* Main Content */}
          <div className="flex flex-col flex-1 ">
            {/* Navbar */}
            <Navbar />

            {/* Main Section */}
            <main className="flex-1 p-4 bg-transparent overflow-auto">
              {children}
            </main>

            {/* Footer */}
            <Footer />
          </div>
        </div>
      </body>
    </html>
  );
}
